#!/bin/env bash

if [ -n "${_IGNIS_ENVIRONMENT_ENABLED}" ]; then
  return
fi
export _IGNIS_ENVIRONMENT_ENABLED=1

if [ -n "${_IGNIS_ENVIRONMENT}" ]; then
  source "${_IGNIS_ENVIRONMENT}"
fi

if [ -z "${HOST_HOSTNAME}" ]; then
  export HOST_HOSTNAME=$(hostname)
fi

export IGNIS_JOB_ID=$(envsubst<<<"${IGNIS_SCHEDULER_ENV_JOB}")
export IGNIS_JOB_CONTAINER_ID=$(envsubst<<<"${IGNIS_SCHEDULER_ENV_CONTAINER}")
export IGNIS_JOB_DIR="${IGNIS_WDIR}/${IGNIS_JOB_ID}"

if [ -n "${IGNIS_TMPDIR}" ];then
  export IGNIS_JOB_CONTAINER_DIR=${IGNIS_TMPDIR}/tmp
  export IGNIS_JOB_SOCKETS=${IGNIS_TMPDIR}/sockets
else
  export IGNIS_JOB_CONTAINER_DIR=${IGNIS_JOB_DIR}/tmp/${IGNIS_JOB_CONTAINER_ID}
  export IGNIS_JOB_SOCKETS=${IGNIS_JOB_DIR}/sockets
fi

for FILE in ${IGNIS_HOME}/env.d/* ; do
  if [ -f "$FILE" ]; then
    source "$FILE"
  fi
done
