#!/bin/env bash

if [ -n "${IGNIS_TMPDIR}" ] && [ -f "${IGNIS_TMPDIR}/environment" ]; then
  source "${IGNIS_TMPDIR}/environment"
fi

if [ -z "${HOST_HOSTNAME}" ]; then
  export HOST_HOSTNAME=$(hostname)
fi

export IGNIS_JOB_ID=$(envsubst<<<"${IGNIS_SCHEDULER_ENV_JOB}")
export IGNIS_JOB_CONTAINER_ID=$(envsubst<<<"${IGNIS_SCHEDULER_ENV_CONTAINER}")
export IGNIS_JOB_DIR="${IGNIS_WDIR}/${IGNIS_JOB_ID}"

if [ -n "${IGNIS_TMPDIR}" ];then
  export IGNIS_JOB_CONTAINER_DIR=${IGNIS_TMPDIR}
else
  export IGNIS_JOB_CONTAINER_DIR=${IGNIS_JOB_DIR}/tmp/${IGNIS_JOB_CONTAINER_ID}/
fi


